name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip scipy
          python -m pip install pytest
          python -m pip install pytest-cov
          python -m pip install pytest-check

      - name: Install current package
        shell: bash -l {0}
        run: |
          python -m pip install -e .

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          python -c "import sys; print('\n'.join(sys.path))"
          python -m pytest --cov=scipy_dispatch tests/ -vvv
          bash <(curl -s https://codecov.io/bash)
